version: '3.3'

services:
  web:
    image: django
    command: 
      sh -c "python manage.py migrate &&
      python manage.py collectstatic --no-input &&
      python manage.py runserver 0.0.0.0:8000 --insecure"
    volumes:
      - ./code:/code
    ports:
      - 8000:8000
    depends_on:
      - celery
      - flower
  flower:
    image: django
    command: flower -A ourcase --port=5555
    ports:
      - 5555:5555
    depends_on:
      - celery
  celery:
    image: django
    command: celery worker -A ourcase -l info --concurrency=1
    depends_on:
      - celery-beat
  celery-beat:
    build: .
    image: django
    command: celery -A ourcase beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    depends_on:
      - db
      - rabbitmq
  db:
    image: postgres:10.1-alpine
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
  rabbitmq:
    image: rabbitmq:latest
    hostname: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=pass